### PR TITLE
Fix untracked files includes non-python files

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by Bachmann1234** [comment]
@kasium we support languages besides python though, I dont understand

**Comment by kasium** [comment]
Oh, that true. Sorry for that.

Files starting with a space seem to have issues in git. Git tells in the diff, that the file starts without a space leading to an issue. Any clue how to fix that?

**Comment by Bachmann1234** [comment]
Ill take a look and see what I can figure out. I might be able to look into this tonight. But if not its going to have to wait till next week because I will not be in a position to do any real programming work for a few days.

**Comment by kasium** [comment]
Thanks a lot. Let me open a dedicated issue for that

**Pull request closed without merging**
