### PR TITLE
Improve usage of flake8

### PR DESCRIPTION
**Pull request by kasium**
This change improves the project internal usage of flake8.
* First, instead of running pydocstyle and pyflakes standalone, we could use flake8 directly
* Second, a configuration for flake8 was added
* Third: existing flake8 vialoations are now resolved. This means, running 'flake8 diff_cover' doesn't return any error

### CODE REVIEW

**Comment by Bachmann1234** [comment]
hmm, this one is showing code changes but I think my github actions flow is not running.

I used to use TravisCI but they started charging and this project does not have revenue... I suspect I just have the hook running in master. Ill try and look as soon as I have a free evening

**Comment by Bachmann1234** [comment]
@kasium please update this one from master. I wanna say the PR build will run after you do that.

**Comment by kasium** [comment]
@Bachmann1234 done

**Comment by Bachmann1234** [comment]
Alrighty. lets merge this Thanks!

**Pull request merged**
