### PR TITLE
Allow eslint to work with other source paths

### LINKED ISSUE #81: diff-quality doesn't work with eslint
I have a git repo with python and javascript files. The structure is:
```
- docker
- scripts
- my_project
--- static
------ .eslintrc.js
------ package.json
------ js
--- app1
--- app2
```
The structure is typical for django projects.
Eslint generates reports with absolute path by default, e.g.
`/home/godlark/PycharmProjects/mye_repo/my_project/static/js/index.js`
but `diff-quality` expects paths relative to the root directory of repo, e.g.
`my_projects/static/js/index.js`
I was able to create a custom formatter for eslint to generate reports with relative path, e.g.
`js/index.js`
But it still doesn't match. The solution is to run in `diff-cover` command `git diff --relative` instead `git diff`

### PR DESCRIPTION
**Pull request by kasium**
Resolves #81

### CODE REVIEW

**Comment by kasium** [comment]
@Bachmann1234 can you please take a deeper look into this? It's not an issue to have a kwargs in the eslint driver, but to provide it to the method. Basically all drivers and reports need to be enables to handle it properly, etc. Do you have any clue?

**Comment by Bachmann1234** [comment]
ill take a look at this in the next couple days

**Comment by Bachmann1234** [comment]
im sorry. I am thinking this is going to take me longer than I had originally hoped. I am alive. Just lot going on and its gonna be hard to make time for open source stuff for a bit. 

Could still happen later this week, but next week is looking more likely.

**Comment by Bachmann1234** [comment]
@kasium so looking at this I wonder if the solution is a post initialization step. 

Essentially adding a method to `QualityDriver` allowing us to pass user args in. Would not break the interface and would be fairly easy to add right? I don't love that it forces us to add state but in theory that state would clear out as soon as the tool was done running. Not like diff-quality is a long running process.

**Comment by kasium** [comment]
Sounds feasibly since we have the driver instance in the `diff_quality_tool.py`. Let me give it a try

**Comment by kasium** [comment]
@Bachmann1234 worked, please have a look

**Comment by Bachmann1234** [comment]
Alright! Lets get this out

**Comment by Bachmann1234** [comment]
thanks for the pr!

**Comment by Bachmann1234** [comment]
released ! https://pypi.org/project/diff-cover/6.4.0/

**Pull request merged**
