### PR TITLE
Update CHANGELOG

### PR DESCRIPTION
**Pull request by itayB**
this change needs to be documented, it broke some ci-cds pipelines :)
https://github.com/Bachmann1234/diff_cover/commit/f40a9579cf2df85e867cd86123ab8bd3ae55fbff

### CODE REVIEW

**Comment by Bachmann1234** [comment]
@itayB this is documented. Please see version 6.0 that's when the change happened. It's why I bumped it up from 5 to 6

**Comment by Bachmann1234** [comment]
here is the line https://github.com/Bachmann1234/diff_cover/blob/main/CHANGELOG#L22

@itayB per that line just add `--compare-branch origin/master` to your build and it should work. Let me know if there are any problems

**Comment by itayB** [comment]
Yea, I tried that but it looks like it run twice, first time with my master branch and then with the main (which doesn't exist).

**Comment by Bachmann1234** [comment]
If you can provide some more details or perhaps a small repo that demonstrates the issue I would be able to look into it.

Its surprising to me because I tired to be careful to ensure this flow works. I changed the default, updated our CI to have that parameter. Only after builds like that passed did I change this repos default branch to a 'main'

**Pull request closed without merging**
