### PR TITLE
Add line numbers to Markdown code snippets

### PR DESCRIPTION
**Pull request by walles**
# With these changes

```
  37 
  38 	}
  39 
  40 	private static void untested() {
! 41 		System.out.println("This method has no tests");
! 42 	}
  43 
  44 }

```

# Before

```

	}

	private static void untested() {
		System.out.println("This method has no tests");
	}

}

```

### CODE REVIEW

**Comment by walles** [comment]
Sorry about the test failures, will fix.

**Comment by walles** [comment]
Tests pass for me locally now.

**Review by Bachmann1234 — APPROVED** [review]
Thanks for the PR, merging this in.

**Comment by Bachmann1234** [comment]
Released in https://pypi.org/project/diff-cover/9.0.0/

Thanks again!

**Pull request merged**
