### PR TITLE
- no context in diff

### PR DESCRIPTION
**Pull request by maho**
don't include any context in diff, so there is no report for lines
which aren't in fact failed

### CODE REVIEW

**Comment by Bachmann1234** [comment]
nice! Fix the tests and ill merge and release this guy. 

Thanks for the PR

**Comment by maho** [comment]
tests are fixed

**Comment by Bachmann1234** [comment]
Released ! https://pypi.org/project/diff-cover/2.6.0/

**Comment by Bachmann1234** [comment]
Thanks again for the PR!

**Pull request merged**
